//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAgenda.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineAgendaEntities : DbContext
    {
        public OnlineAgendaEntities()
            : base("name=OnlineAgendaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAgendaItem> TblAgendaItem { get; set; }
        public virtual DbSet<TblBijlage> TblBijlage { get; set; }
        public virtual DbSet<TblDocent> TblDocent { get; set; }
        public virtual DbSet<TblKlas> TblKlas { get; set; }
        public virtual DbSet<tblPost> tblPost { get; set; }
        public virtual DbSet<TblStudent> TblStudent { get; set; }
        public virtual DbSet<TblVak> TblVaks { get; set; }
    }
}
