//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAgenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAgendaItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblAgendaItem()
        {
            this.tblPosts = new HashSet<tblPost>();
            this.TblBijlages = new HashSet<TblBijlage>();
        }
    
        public int Id { get; set; }
        public System.DateTime DatumTijd { get; set; }
        public string Omschrijving { get; set; }
        public string Soort { get; set; }
        public string VakCode { get; set; }
        public string Klas { get; set; }
        public string Docentcode { get; set; }
        public string ForumStatus { get; set; }
    
        public virtual TblDocent TblDocent { get; set; }
        public virtual TblKlas TblKlas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPost> tblPosts { get; set; }
        public virtual TblVak TblVak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBijlage> TblBijlages { get; set; }
    }
}
