//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAgenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDocent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblDocent()
        {
            this.TblAgendaItems = new HashSet<TblAgendaItem>();
            this.TblKlas = new HashSet<TblKlas>();
        }
    
        public string Afkorting { get; set; }
        public string Aanhef { get; set; }
        public string Voorletters { get; set; }
        public string GebruikersId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAgendaItem> TblAgendaItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblKlas> TblKlas { get; set; }
    }
}
