//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAgenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPost
    {
        public string GebruikerId { get; set; }
        public int AgendaItemId { get; set; }
        public System.DateTime PostDatumTijd { get; set; }
        public string Post { get; set; }
    
        public virtual TblAgendaItem TblAgendaItem { get; set; }
    }
}
