//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAgenda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudent
    {
        public string StudentNummer { get; set; }
        public Nullable<System.DateTime> Geboortedatum { get; set; }
        public string Adres { get; set; }
        public string Postcode { get; set; }
        public string Plaats { get; set; }
        public string Klas { get; set; }
        public string GebruikersId { get; set; }
    
        public virtual TblKlas TblKlas { get; set; }
    }
}
