// <auto-generated />
namespace SoccerHub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedAttendances : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedAttendances));
        
        string IMigrationMetadata.Id
        {
            get { return "201710051202498_addedAttendances"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
