// <auto-generated />
namespace tv_series.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bigbang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bigbang));
        
        string IMigrationMetadata.Id
        {
            get { return "201710041244296_bigbang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
